baseURL = 'https://miawinter.de/'
languageCode = 'en-us'
timeZone= 'Europe/Berlin'
title = 'Mia Winter'

[menu]
[[menu.main]]
    identifier = "home"
    name = 'Home'
    url = '/'
    weight = -100
[[menu.main]]
    identifier = "privacy"
    name = "Privacy"
    url = "/privacy"
    weight = -50
[[menu.main]]
    identifier = "pgp"
    name = "PGP"
    url = "/pgp"
    weight = -51

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true