name: hugo-deploy
run-name: build and deploy hugo page
on:
    push:
        branches:
          - main
defaults:
    run:
        shell: bash
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            HUGO_VERSION: 0.111.3
        steps:
          - uses: actions/checkout@v3
          - name: Install Hugo CLI
            run: |
                wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
                && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          - name: Install Dart Sass Embedded
            run: sudo snap install dart-sass-embedded
          - name: Install Node.js dependencies
            run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
          - name: Install ssh key
            run: |
                sudo ssh-agent sh
                sudo echo "${{ secrets.SSH_PRIVATE_KEY }}" | sudo tr -d '\r' | sudo ssh-add -
                sudo mkdir -p ~/.ssh
                sudo chmod 700 ~/.ssh
                sudo echo "${{ secrets.KNOWN_HOST_KEY }}" > ~/.ssh/known_hosts
          - name: Build with Hugo
            env:
                # For maximum backward compatibility with Hugo modules
                HUGO_ENVIRONMENT: production
                HUGO_ENV: production
            run: hugo --gc --minify
          - name: Deploy with rsync
            run: rsync -atv --delete --progress --checksum --whole-file public_html/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/todo
