name: hugo-deploy
run-name: build and deploy hugo page
on:
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            HUGO_VERSION: 0.111.3
        steps:
          - uses: actions/checkout@v2
          - name: Install Hugo CLI
            run: |
                wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
                && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          - name: Install Dart Sass Embedded
            run: sudo snap install dart-sass-embedded
          - name: Install Node.js dependencies
            run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
          - name: Install rsync and ssh key
            run:
                - apk update && apk add openssh-client rsync
                - eval $(ssh-agent -s)
                - echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
                - mkdir -p ~/.ssh
                - chmod 700 ~/.ssh
                - echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/known_hosts
          - name: Build with Hugo
            env:
                # For maximum backward compatibility with Hugo modules
                HUGO_ENVIRONMENT: production
                HUGO_ENV: production
            run: hugo --gc --minify
          - name: Deploy with rsync
            run: rsync -atv --delete --progress --checksum --whole-file public_html/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/todo
